[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]

# ffi= true allows tu run command in the terminal, use with caution (Interactions.s.sol)
ffi= true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
